import { PDFToolDef, ToolCategory } from '@/types/tools';

export const TOOL_CATEGORIES: ToolCategory[] = [
  'Organize PDF',
  'Optimize PDF',
  'Convert to PDF',
  'Convert from PDF',
  'Edit PDF',
  'PDF Security',
  'PDF Intelligence',
];

export const PDF_TOOLS: PDFToolDef[] = [
  // ─── ORGANIZE PDF ───────────────────────────────────────────────
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    title: 'Merge PDF',
    shortTitle: 'Merge',
    description: 'Combine multiple PDF files into one document in your exact preferred order.',
    category: 'Organize PDF',
    badge: 'Popular',
    icon: 'Layers',
    accentColor: '#ff5a36',
    isReady: true,
    isMultiFile: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/merge',
    metaTitle: 'Merge PDF Online Free – Combine Multiple PDF Files | PustakEdits',
    metaDescription: 'Combine and merge multiple PDF files into a single document for free. Fast, secure, and private browser-based PDF merger.',
    keywords: ['merge pdf', 'combine pdf', 'join pdf files', 'free pdf merger', 'online pdf joiner'],
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    title: 'Split PDF',
    shortTitle: 'Split',
    description: 'Separate one page or a whole range for easy conversion into independent PDF files.',
    category: 'Organize PDF',
    badge: 'Popular',
    icon: 'Scissors',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/split',
    metaTitle: 'Split PDF Online Free – Extract Pages from PDF | PustakEdits',
    metaDescription: 'Split a PDF into individual pages or custom page ranges with zero quality loss. Free online PDF splitter.',
    keywords: ['split pdf', 'separate pdf pages', 'extract pdf pages', 'cut pdf'],
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    title: 'Remove Pages',
    shortTitle: 'Remove Pages',
    description: 'Delete unwanted or blank pages from your PDF document instantly.',
    category: 'Organize PDF',
    icon: 'Trash2',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/delete-pages',
    metaTitle: 'Delete PDF Pages Online Free – Remove Pages from PDF | PustakEdits',
    metaDescription: 'Delete and remove specific pages from any PDF document quickly and securely. Free online tool.',
    keywords: ['remove pdf pages', 'delete pages from pdf', 'cut pages pdf'],
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    title: 'Extract Pages',
    shortTitle: 'Extract Pages',
    description: 'Select specific pages and save them as a brand new, standalone PDF document.',
    category: 'Organize PDF',
    icon: 'FileOutput',
    accentColor: '#4c7fff',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/extract-pages',
    metaTitle: 'Extract PDF Pages Free – Export Pages to New PDF | PustakEdits',
    metaDescription: 'Extract pages from your PDF document and create a new PDF containing only the pages you need.',
    keywords: ['extract pdf pages', 'save pages as pdf', 'export pdf page'],
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    shortTitle: 'Rotate',
    description: 'Rotate your PDF pages 90, 180, or 270 degrees clockwise to fix document orientation.',
    category: 'Organize PDF',
    icon: 'RotateCw',
    accentColor: '#ffcc4d',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/rotate',
    metaTitle: 'Rotate PDF Online Free – Rotate PDF Pages Permanently | PustakEdits',
    metaDescription: 'Rotate PDF pages 90, 180, or 270 degrees permanently. Fast and free online PDF rotation tool.',
    keywords: ['rotate pdf', 'turn pdf', 'rotate pdf 90 degrees', 'flip pdf orientation'],
  },

  // ─── OPTIMIZE PDF ───────────────────────────────────────────────
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    title: 'Compress PDF',
    shortTitle: 'Compress',
    description: 'Reduce PDF file size while maintaining high quality. Choose Extreme, Recommended, or Low compression.',
    category: 'Optimize PDF',
    badge: 'Popular',
    icon: 'Minimize2',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/compress',
    metaTitle: 'Compress PDF Online Free – Reduce PDF File Size | PustakEdits',
    metaDescription: 'Reduce PDF file size without losing visual quality. Free online PDF compressor with custom presets.',
    keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'pdf size reducer', 'free pdf compressor'],
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    title: 'Repair PDF',
    shortTitle: 'Repair',
    description: 'Recover and reconstruct data from corrupted, unreadable, or damaged PDF documents.',
    category: 'Optimize PDF',
    icon: 'Wrench',
    accentColor: '#4c7fff',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/repair',
    metaTitle: 'Repair Corrupted PDF Online Free – Fix Damaged PDF | PustakEdits',
    metaDescription: 'Fix and repair damaged or broken PDF files online. Reconstruct cross-reference tables and recover content.',
    keywords: ['repair pdf', 'fix corrupted pdf', 'restore pdf', 'recover damaged pdf'],
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    title: 'OCR PDF',
    shortTitle: 'OCR PDF',
    description: 'Make scanned and raster PDFs fully searchable and selectable.',
    category: 'Optimize PDF',
    badge: 'New',
    icon: 'Scan',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf,.png,.jpg,.jpeg,.webp,.tiff',
    apiEndpoint: '/api/tools/ocr',
    metaTitle: 'OCR PDF Online Free – Make PDF Searchable | PustakEdits',
    metaDescription: 'Convert scanned PDF documents into searchable text files online with OCR.',
    keywords: ['ocr pdf', 'searchable pdf', 'recognize text pdf', 'scanned pdf to text'],
  },
  {
    id: 'flatten-pdf',
    slug: 'flatten-pdf',
    title: 'Flatten PDF',
    shortTitle: 'Flatten',
    description: 'Merge form fields and interactive annotations directly into the permanent PDF page layer.',
    category: 'Optimize PDF',
    icon: 'Layers',
    accentColor: '#ffcc4d',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/flatten',
    metaTitle: 'Flatten PDF Online Free – Lock Form Fields & Annotations | PustakEdits',
    metaDescription: 'Flatten interactive forms, signatures, and annotations into static PDF content so they cannot be altered.',
    keywords: ['flatten pdf', 'lock pdf form', 'bake annotations pdf', 'flatten fillable pdf'],
  },
  {
    id: 'grayscale-pdf',
    slug: 'grayscale-pdf',
    title: 'Grayscale PDF',
    shortTitle: 'Grayscale',
    description: 'Convert color PDF documents into clean, black and white or monochrome files.',
    category: 'Optimize PDF',
    icon: 'Layers',
    accentColor: '#6B7280',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/grayscale',
    metaTitle: 'Convert PDF to Grayscale Black and White Online Free | PustakEdits',
    metaDescription: 'Convert color PDFs to monochrome or black and white for smaller file size and crisp printing.',
    keywords: ['grayscale pdf', 'black and white pdf', 'monochrome pdf', 'color to bw pdf'],
  },

  // ─── CONVERT TO PDF ─────────────────────────────────────────────
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF',
    shortTitle: 'JPG to PDF',
    description: 'Convert JPG, PNG, and WebP images into high-quality PDF documents in seconds.',
    category: 'Convert to PDF',
    badge: 'Popular',
    icon: 'Image',
    accentColor: '#ff5a36',
    isReady: true,
    isMultiFile: true,
    acceptTypes: 'image/*',
    apiEndpoint: '/api/tools/images-to-pdf',
    metaTitle: 'Convert JPG to PDF Online Free – Image to PDF Converter | PustakEdits',
    metaDescription: 'Convert PNG, JPG, and image files into a single multi-page PDF document. Free and instant.',
    keywords: ['jpg to pdf', 'image to pdf', 'convert photos to pdf', 'png to pdf'],
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    shortTitle: 'Word to PDF',
    description: 'Convert Microsoft Word DOCX documents into clean, formatted PDF documents.',
    category: 'Convert to PDF',
    badge: 'Popular',
    icon: 'FileText',
    accentColor: '#4c7fff',
    isReady: true,
    acceptTypes: '.docx,.doc',
    apiEndpoint: '/api/tools/word-to-pdf',
    metaTitle: 'Word to PDF Converter Online Free – Convert DOCX to PDF | PustakEdits',
    metaDescription: 'Convert Microsoft Word documents (DOCX and DOC) to PDF online for free with formatting preservation.',
    keywords: ['word to pdf', 'docx to pdf', 'convert word to pdf', 'doc to pdf'],
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    shortTitle: 'PPT to PDF',
    description: 'Convert Microsoft PowerPoint PPTX presentations into easy-to-read PDF slides.',
    category: 'Convert to PDF',
    icon: 'Presentation',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pptx,.ppt',
    apiEndpoint: '/api/tools/powerpoint-to-pdf',
    metaTitle: 'PowerPoint to PDF Converter Online Free – Convert PPTX to PDF | PustakEdits',
    metaDescription: 'Convert PowerPoint slides (PPTX and PPT) to PDF online for free.',
    keywords: ['powerpoint to pdf', 'pptx to pdf', 'convert presentation to pdf'],
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    title: 'Excel to PDF',
    shortTitle: 'Excel to PDF',
    description: 'Convert Excel spreadsheets (XLSX, XLS) into formatted, printable PDF tables.',
    category: 'Convert to PDF',
    icon: 'FileSpreadsheet',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.xlsx,.xls',
    apiEndpoint: '/api/tools/excel-to-pdf',
    metaTitle: 'Excel to PDF Converter Online Free – Convert XLSX to PDF | PustakEdits',
    metaDescription: 'Convert Microsoft Excel spreadsheets to PDF online for free.',
    keywords: ['excel to pdf', 'xlsx to pdf', 'spreadsheet to pdf'],
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    title: 'HTML to PDF',
    shortTitle: 'HTML to PDF',
    description: 'Convert HTML files, articles, and webpage snippets into clean PDF pages.',
    category: 'Convert to PDF',
    icon: 'Globe',
    accentColor: '#ffcc4d',
    isReady: true,
    acceptTypes: '.html,.htm,text/html',
    apiEndpoint: '/api/tools/html-to-pdf',
    metaTitle: 'HTML to PDF Converter Online Free | PustakEdits',
    metaDescription: 'Convert HTML documents, code, and web content into PDF format online.',
    keywords: ['html to pdf', 'webpage to pdf', 'url to pdf', 'html code to pdf'],
  },

  // ─── CONVERT FROM PDF ───────────────────────────────────────────
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG',
    shortTitle: 'PDF to JPG',
    description: 'Extract PDF pages as high-resolution PNG or JPG images, downloadable individually or as a ZIP.',
    category: 'Convert from PDF',
    badge: 'Popular',
    icon: 'FileImage',
    accentColor: '#ffcc4d',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-images',
    metaTitle: 'PDF to JPG Online Free – Convert PDF Pages to Images | PustakEdits',
    metaDescription: 'Extract and convert every PDF page into high-quality JPG or PNG images. Free online converter.',
    keywords: ['pdf to jpg', 'pdf to image', 'convert pdf to png', 'export pdf as pictures'],
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    title: 'PDF to Word',
    shortTitle: 'PDF to Word',
    description: 'Convert PDF documents into fully editable Microsoft Word DOCX files.',
    category: 'Convert from PDF',
    badge: 'Popular',
    icon: 'FileText',
    accentColor: '#4c7fff',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-word',
    metaTitle: 'PDF to Word Online Free – Convert PDF to Editable DOCX | PustakEdits',
    metaDescription: 'Convert PDF to editable DOCX format while accurately reconstructing paragraphs, tables, and fonts.',
    keywords: ['pdf to word', 'convert pdf to docx', 'editable pdf to word', 'pdf to doc'],
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    shortTitle: 'PDF to PPT',
    description: 'Convert PDF pages into high-definition Microsoft PowerPoint PPTX presentation slides.',
    category: 'Convert from PDF',
    badge: 'Popular',
    icon: 'Presentation',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-powerpoint',
    metaTitle: 'PDF to PowerPoint Online Free – Convert PDF to PPTX Slides | PustakEdits',
    metaDescription: 'Convert PDF documents into editable Microsoft PowerPoint presentation slides.',
    keywords: ['pdf to powerpoint', 'pdf to pptx', 'convert pdf to presentation slides'],
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    title: 'PDF to Excel',
    shortTitle: 'PDF to Excel',
    description: 'Extract tables and structured financial data from PDF documents into Excel spreadsheets (.xlsx).',
    category: 'Convert from PDF',
    icon: 'FileSpreadsheet',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-excel',
    metaTitle: 'PDF to Excel Online Free – Extract Tables from PDF to XLSX | PustakEdits',
    metaDescription: 'Extract tables and spreadsheet data from PDF into editable Microsoft Excel XLSX files.',
    keywords: ['pdf to excel', 'pdf to xlsx', 'extract tables from pdf', 'pdf table converter'],
  },
  {
    id: 'pdf-to-pdfa',
    slug: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    shortTitle: 'PDF to PDF/A',
    description: 'Convert documents to ISO-standardized PDF/A format for legal compliance and long-term archiving.',
    category: 'Convert from PDF',
    icon: 'FileArchive',
    accentColor: '#ffcc4d',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-pdfa',
    metaTitle: 'Convert PDF to PDF/A Online Free – Long-Term Archiving | PustakEdits',
    metaDescription: 'Convert your PDF documents to ISO-standard PDF/A for archiving and compliance.',
    keywords: ['pdf to pdfa', 'pdf archive format', 'pdf/a converter', 'iso standard pdf'],
  },
  {
    id: 'pdf-to-text',
    slug: 'pdf-to-text',
    title: 'PDF to Text',
    shortTitle: 'PDF to Text',
    description: 'Extract raw text or clean markdown from any text-based PDF document instantly.',
    category: 'Convert from PDF',
    icon: 'FileCode',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-text',
    metaTitle: 'PDF to Text & Markdown Free – Extract Text from PDF | PustakEdits',
    metaDescription: 'Extract the text layer from your PDF document into plain text (.txt) or markdown (.md).',
    keywords: ['pdf to text', 'extract text from pdf', 'pdf to txt', 'pdf to markdown'],
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    title: 'PDF to Markdown',
    shortTitle: 'PDF to MD',
    description: 'Convert PDF documents into formatted Markdown (.md) for LLM analysis, AI pipelines, and documentation.',
    category: 'Convert from PDF',
    badge: 'AI',
    icon: 'FileCode',
    accentColor: '#4c7fff',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/pdf-to-text',
    metaTitle: 'PDF to Markdown Online Free – Convert PDF to MD | PustakEdits',
    metaDescription: 'Convert PDF files into clean, structured Markdown for notes, AI models, and developer docs.',
    keywords: ['pdf to markdown', 'pdf to md', 'ai pdf to text', 'pdf markdown converter'],
  },

  // ─── EDIT PDF ───────────────────────────────────────────────────
  {
    id: 'edit-pdf',
    slug: 'edit-pdf',
    title: 'Edit PDF Text',
    shortTitle: 'Edit Text',
    description: 'Directly rewrite the actual font vector text layer inside your PDF. No white boxes or overlays.',
    category: 'Edit PDF',
    badge: 'Flagship',
    icon: 'Pencil',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/dashboard',
    metaTitle: 'Edit PDF Text Online Free – True Text Layer Rewriter | PustakEdits',
    metaDescription: 'Edit the actual text layer inside your PDF document without white-box overlays. Matches original fonts and styling.',
    keywords: ['edit pdf text', 'modify pdf text', 'true pdf text editor', 'free pdf text editor'],
  },
  {
    id: 'add-page-numbers',
    slug: 'add-page-numbers',
    title: 'Add Page Numbers',
    shortTitle: 'Page Numbers',
    description: 'Insert customizable page numbers into your PDF with flexible position and format controls.',
    category: 'Edit PDF',
    badge: 'Popular',
    icon: 'Binary',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/page-numbers',
    metaTitle: 'Add Page Numbers to PDF Online Free | PustakEdits',
    metaDescription: 'Number PDF pages online for free. Choose header or footer placement, custom numbering formats, and styles.',
    keywords: ['add page numbers to pdf', 'number pdf pages', 'pdf pagination', 'page numbering online'],
  },
  {
    id: 'add-watermark',
    slug: 'add-watermark',
    title: 'Add Watermark',
    shortTitle: 'Watermark',
    description: 'Stamp custom text watermarks across pages with controllable opacity, rotation, and colors.',
    category: 'Edit PDF',
    badge: 'Popular',
    icon: 'Stamp',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/watermark',
    metaTitle: 'Add Watermark to PDF Online Free – Custom Text & Stamp | PustakEdits',
    metaDescription: 'Protect and brand documents by adding custom text watermarks with opacity and rotation settings. Free online tool.',
    keywords: ['add watermark to pdf', 'stamp pdf', 'watermark pdf online', 'confidential watermark pdf'],
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    title: 'Crop PDF',
    shortTitle: 'Crop',
    description: 'Trim margins, reduce white space, and adjust document dimensions.',
    category: 'Edit PDF',
    icon: 'Crop',
    accentColor: '#ffcc4d',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/crop',
    metaTitle: 'Crop PDF Margins Online Free | PustakEdits',
    metaDescription: 'Crop PDF pages and trim document margins with precision. Free online PDF cropper.',
    keywords: ['crop pdf', 'trim pdf margins', 'resize pdf pages', 'cut pdf margins'],
  },

  // ─── PDF SECURITY ───────────────────────────────────────────────
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    title: 'Protect PDF',
    shortTitle: 'Protect',
    description: 'Encrypt your PDF with standard AES-256 password protection to prevent unauthorized opening.',
    category: 'PDF Security',
    badge: 'Popular',
    icon: 'Lock',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/protect',
    metaTitle: 'Password Protect PDF Online Free – Encrypt PDF AES-256 | PustakEdits',
    metaDescription: 'Encrypt your sensitive PDF files with a secure password using 256-bit AES encryption. Free and private.',
    keywords: ['protect pdf', 'encrypt pdf', 'lock pdf with password', 'add password to pdf'],
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    title: 'Unlock PDF',
    shortTitle: 'Unlock',
    description: 'Remove password and security restrictions from an encrypted PDF document.',
    category: 'PDF Security',
    icon: 'Unlock',
    accentColor: '#2fd6c4',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/unlock',
    metaTitle: 'Unlock PDF Online Free – Remove PDF Password | PustakEdits',
    metaDescription: 'Unlock password-protected PDF files and remove security restrictions easily. Free online PDF unlocker.',
    keywords: ['unlock pdf', 'remove pdf password', 'decrypt pdf', 'remove restrictions pdf'],
  },
  {
    id: 'redact-pdf',
    slug: 'redact-pdf',
    title: 'Redact PDF',
    shortTitle: 'Redact',
    description: 'Permanently black out and sanitize confidential text, numbers, and private data.',
    category: 'PDF Security',
    badge: 'New',
    icon: 'EyeOff',
    accentColor: '#ff5a36',
    isReady: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/redact',
    metaTitle: 'Redact PDF Online Free – Black Out Confidential Text | PustakEdits',
    metaDescription: 'Permanently remove and black out confidential text, names, and numbers from PDF documents.',
    keywords: ['redact pdf', 'black out text pdf', 'sanitize pdf', 'hide sensitive info pdf'],
  },
  {
    id: 'compare-pdf',
    slug: 'compare-pdf',
    title: 'Compare PDF',
    shortTitle: 'Compare',
    description: 'Compare two PDF documents side by side to instantly identify changes and visual differences.',
    category: 'PDF Security',
    badge: 'New',
    icon: 'GitCompare',
    accentColor: '#4c7fff',
    isReady: true,
    isMultiFile: true,
    acceptTypes: '.pdf',
    apiEndpoint: '/api/tools/compare',
    metaTitle: 'Compare PDF Files Online Free – Side-by-Side PDF Diff | PustakEdits',
    metaDescription: 'Compare two PDF documents side by side to spot differences, edits, and revisions.',
    keywords: ['compare pdf', 'pdf diff', 'side by side pdf comparison', 'find changes in pdf'],
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    title: 'Sign PDF',
    shortTitle: 'Sign',
    description: 'Sign documents digitally or create custom signatures to certify agreements.',
    category: 'PDF Security',
    badge: 'Soon',
    icon: 'PenTool',
    accentColor: '#4c7fff',
    isReady: false,
    metaTitle: 'Sign PDF Online Free – Electronic Signatures | PustakEdits',
    metaDescription: 'Sign contracts and PDF documents electronically with secure signature stamps.',
    keywords: ['sign pdf', 'electronic signature pdf', 'fill and sign pdf'],
  },

  // ─── PDF INTELLIGENCE (AI) ──────────────────────────────────────
  {
    id: 'ai-summarizer',
    slug: 'ai-summarizer',
    title: 'AI Summarizer',
    shortTitle: 'AI Summary',
    description: 'Get concise executive summaries, key takeaways, and action items from any PDF document.',
    category: 'PDF Intelligence',
    badge: 'AI',
    icon: 'Sparkles',
    accentColor: '#4c7fff',
    isReady: false,
    metaTitle: 'AI PDF Summarizer Online – Instant Document Analysis | PustakEdits',
    metaDescription: 'Summarize long PDF research papers, contracts, and books using AI. Fast, accurate, and structured takeaways.',
    keywords: ['ai pdf summarizer', 'summarize pdf with ai', 'pdf analysis ai', 'extract summary from pdf'],
  },
  {
    id: 'translate-pdf',
    slug: 'translate-pdf',
    title: 'Translate PDF',
    shortTitle: 'Translate',
    description: 'Translate documents into over 50 languages while preserving layout and structure.',
    category: 'PDF Intelligence',
    badge: 'AI',
    icon: 'Languages',
    accentColor: '#2fd6c4',
    isReady: false,
    metaTitle: 'Translate PDF Online Free – AI Document Translator | PustakEdits',
    metaDescription: 'Translate PDF files into multiple languages with AI while retaining original document layout.',
    keywords: ['translate pdf', 'ai document translator', 'pdf translation tool'],
  },
];

export function getToolBySlug(slug: string): PDFToolDef | undefined {
  return PDF_TOOLS.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): PDFToolDef[] {
  return PDF_TOOLS.filter((tool) => tool.category === category);
}
